config/routes.rb
Rails.application.routes.draw do
  resources :sound_products

  resources :lighting_products

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :promotions

  get 'community/index'

  get 'productinfo/sound'

  get 'productinfo/light'

    get 'home/search'
    post 'home/search'

resources :lightingconsoles

  resources :lightingaccessories

  resources :lightingcables

  resources :movingfixtures

  resources :ledfixtures

  resources :conventionalfixtures

  resources :amplifers

  resources :speakers

  resources :soundcables

  resources :soundconsoles

  resources :wiredmics

  resources :wirelessmics

  resources :employees

  resources :rentals

  resources :newsales

  resources :suppliers

  resources :used_sales

  resources :customers

    get 'home/sales'

    get 'home/rentals'

    get 'home/index'

    get 'home/about'

    get 'home/contact'
    
    get 'home/help'

    get 'home/privacy'
    
    get 'home/info'
    
    get 'home/weekend'
    
    get 'home/announcements'
    get 'home/conditions'
    get 'home/sitemap'

    get "login" => "sessions#new", :as => "login"
delete 'logout' => "sessions#destroy", :as => "logout"
resources :sessions

  root 'home#index'

end

app/models/amplifer.rb
class Amplifer < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :firstname, presence: true
validates :lastname, presence: true

  class EmailValidator < ActiveModel::EachValidator
        def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end
      validates :username, :presence => true, :uniqueness => true
	has_secure_password

end

app/models/employee.rb
class Employee < ActiveRecord::Base
validates :firstname, presence: true
validates :lastname, presence: true

   class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

end

app/models/ledfixture.rb
class Ledfixture < ActiveRecord::Base
end

app/models/lightingcable.rb
class Lightingcable < ActiveRecord::Base
end

app/models/lightingconsole.rb
class Lightingconsole < ActiveRecord::Base
end

app/models/movingfixture.rb
class Movingfixture < ActiveRecord::Base
end

app/models/newsale.rb
class Newsale < ActiveRecord::Base
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
end

app/models/rental.rb
class Rental < ActiveRecord::Base
end

app/models/sound_product.rb
class SoundProduct < ActiveRecord::Base
end

app/models/soundcable.rb
class Soundcable < ActiveRecord::Base
end

app/models/soundconsole.rb
class Soundconsole < ActiveRecord::Base
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
validates :firstname, presence: true
validates :lastname, presence: true
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

end

app/models/used_sale.rb
class UsedSale < ActiveRecord::Base
end

app/models/wiredmic.rb
class Wiredmic < ActiveRecord::Base
end

app/models/wirelessmic.rb
class Wirelessmic < ActiveRecord::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:firstname, :lastname, :address, :city, :state, :zip, :employeeemail, :employeephone)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newsales_helper.rb
module NewsalesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :employeeemail %><br>
    <%= f.text_field :employeeemail %>
  </div>
  <div class="field">
    <%= f.label :employeephone %><br>
    <%= f.text_field :employeephone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Employeeemail</th>
      <th>Employeephone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.firstname %></td>
        <td><%= employee.lastname %></td>
        <td><%= employee.address %></td>
        <td><%= employee.city %></td>
        <td><%= employee.state %></td>
        <td><%= employee.zip %></td>
        <td><%= employee.employeeemail %></td>
        <td><%= employee.employeephone %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @employee.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @employee.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @employee.zip %>
</p>

<p>
  <strong>Employeeemail:</strong>
  <%= @employee.employeeemail %>
</p>

<p>
  <strong>Employeephone:</strong>
  <%= @employee.employeephone %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>