config/routes.rb
Rails.application.routes.draw do
  resources :sound_products

  resources :lighting_products

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :promotions

  get 'community/index'

  get 'productinfo/sound'

  get 'productinfo/light'

    get 'home/search'
    post 'home/search'

resources :lightingconsoles

  resources :lightingaccessories

  resources :lightingcables

  resources :movingfixtures

  resources :ledfixtures

  resources :conventionalfixtures

  resources :amplifers

  resources :speakers

  resources :soundcables

  resources :soundconsoles

  resources :wiredmics

  resources :wirelessmics

  resources :employees

  resources :rentals

  resources :newsales

  resources :suppliers

  resources :used_sales

  resources :customers

    get 'home/sales'

    get 'home/rentals'

    get 'home/index'

    get 'home/about'

    get 'home/contact'
    
    get 'home/help'

    get 'home/privacy'
    
    get 'home/info'
    
    get 'home/weekend'
    
    get 'home/announcements'
    get 'home/conditions'
    get 'home/sitemap'

    get "login" => "sessions#new", :as => "login"
delete 'logout' => "sessions#destroy", :as => "logout"
resources :sessions

  root 'home#index'

end

app/models/amplifer.rb
class Amplifer < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :firstname, presence: true
validates :lastname, presence: true

  class EmailValidator < ActiveModel::EachValidator
        def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end
      validates :username, :presence => true, :uniqueness => true
	has_secure_password

end

app/models/employee.rb
class Employee < ActiveRecord::Base
validates :firstname, presence: true
validates :lastname, presence: true

   class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

end

app/models/ledfixture.rb
class Ledfixture < ActiveRecord::Base
end

app/models/lightingcable.rb
class Lightingcable < ActiveRecord::Base
end

app/models/lightingconsole.rb
class Lightingconsole < ActiveRecord::Base
end

app/models/movingfixture.rb
class Movingfixture < ActiveRecord::Base
end

app/models/newsale.rb
class Newsale < ActiveRecord::Base
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
end

app/models/rental.rb
class Rental < ActiveRecord::Base
end

app/models/sound_product.rb
class SoundProduct < ActiveRecord::Base
end

app/models/soundcable.rb
class Soundcable < ActiveRecord::Base
end

app/models/soundconsole.rb
class Soundconsole < ActiveRecord::Base
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
validates :firstname, presence: true
validates :lastname, presence: true
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

end

app/models/used_sale.rb
class UsedSale < ActiveRecord::Base
end

app/models/wiredmic.rb
class Wiredmic < ActiveRecord::Base
end

app/models/wirelessmic.rb
class Wirelessmic < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 skip_before_filter :authorize

    def index
    @time = Time.now
  end

  def about
    
  end

  def contact
      
  end
    

  def sales
    
  end

  def rentals
    
  end
    
    def help
    
  end
    
    def privacy
    
  end
    def weekend
        @day =Time.now
        @to_saturday = 6- @day.wday
    end
    def search
       @results=0
	if !params[:searchinput].nil?
		@results=1
		@searchcriteria="%#{params[:Input]}%"	
		@productlist = Conventionalfixture.where("fixturename like ?",@searchcriteria)	
    end  
    end
    def announcements
        @promotions = Promotion.where("startdate <= ? AND enddate >= ?",  Date.today, Date.today)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newsales_helper.rb
module NewsalesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/home/about.html.erb
<h1>About</h1>
	<%= link_to "Employees", employees_path %> 
	<%= link_to "Suppliers", suppliers_path %> 

app/views/home/announcements.html.erb
<h1>Announcements</h1>

app/views/home/conditions.html.erb
<h1>Conditions of Use</h1>

app/views/home/contact.html.erb
<h1>Contact</h1>

app/views/home/help.html.erb
<h1>Help</h1>

app/views/home/index.html.erb
<h1>Home</h1>
Current Time is: <%= @time %>

app/views/home/info.html.erb
<h1>Product Information</h1>
		 <%= link_to "Sound Equipment", productinfo_sound_path %> 
		 <%= link_to "Lighting Equipment", productinfo_light_path %> 

app/views/home/privacy.html.erb
<h1>Privacy</h1>

app/views/home/sales.html.erb
<h1>Sales</h1>
	<%= link_to "New Sales", newsales_path %> 
	<%= link_to "Used Sales", used_sales_path %> 

app/views/home/search.html.erb
<p> <h1>Search</h1> </p>

<%= form_tag :action => 'search' do %>
	<p>What product are you looking for?: 
	<%= text_field_tag 'searchinput', @searchinput %> </p>
	<hr/>
	<% if @results>0 %>
		<% if @productlist.length >0 %>
			<p> Here are the search results:</p>
			<p>
			<table>
			<tr>
				<th>Product Name</th>
				<th>Image</th>
			</tr>
			<% @productlist.each do |p| %>
				<tr>
				<td><%= link_to p.fixturename, conventionalfixture_path(p.id) %></td>
				<td><%= p.productimage %></td>
				<td><%= p.fixturemaker %></td>
				</tr>
			<% end %>
			</table>

		<% else%>
			<p>There were no products with your search criteria. Try again!</p>
		<% end %>
	<% end %>

	<%= submit_tag 'Search' %>
<% end %>
	

app/views/home/sitemap.html.erb
<h1>Sitemap</h1>

app/views/home/weekend.html.erb
<h1>Your <em>weekend planner</em></h1>
<p>Cheer up!  You only have <%= @to_saturday %> more day(s) until the start of the next weekend!</p>