config/routes.rb
Rails.application.routes.draw do
  resources :sound_products

  resources :lighting_products

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :promotions

  get 'community/index'

  get 'productinfo/sound'

  get 'productinfo/light'

    get 'home/search'
    post 'home/search'

resources :lightingconsoles

  resources :lightingaccessories

  resources :lightingcables

  resources :movingfixtures

  resources :ledfixtures

  resources :conventionalfixtures

  resources :amplifers

  resources :speakers

  resources :soundcables

  resources :soundconsoles

  resources :wiredmics

  resources :wirelessmics

  resources :employees

  resources :rentals

  resources :newsales

  resources :suppliers

  resources :used_sales

  resources :customers

    get 'home/sales'

    get 'home/rentals'

    get 'home/index'

    get 'home/about'

    get 'home/contact'
    
    get 'home/help'

    get 'home/privacy'
    
    get 'home/info'
    
    get 'home/weekend'
    
    get 'home/announcements'
    get 'home/conditions'
    get 'home/sitemap'

    get "login" => "sessions#new", :as => "login"
delete 'logout' => "sessions#destroy", :as => "logout"
resources :sessions

  root 'home#index'

end

app/models/amplifer.rb
class Amplifer < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :firstname, presence: true
validates :lastname, presence: true

  class EmailValidator < ActiveModel::EachValidator
        def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end
      validates :username, :presence => true, :uniqueness => true
	has_secure_password

end

app/models/employee.rb
class Employee < ActiveRecord::Base
validates :firstname, presence: true
validates :lastname, presence: true

   class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

end

app/models/ledfixture.rb
class Ledfixture < ActiveRecord::Base
end

app/models/lighting_product.rb
class LightingProduct < ActiveRecord::Base
end

app/models/lightingcable.rb
class Lightingcable < ActiveRecord::Base
end

app/models/lightingconsole.rb
class Lightingconsole < ActiveRecord::Base
end

app/models/movingfixture.rb
class Movingfixture < ActiveRecord::Base
end

app/models/newsale.rb
class Newsale < ActiveRecord::Base
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
end

app/models/rental.rb
class Rental < ActiveRecord::Base
end

app/models/sound_product.rb
class SoundProduct < ActiveRecord::Base
end

app/models/soundcable.rb
class Soundcable < ActiveRecord::Base
end

app/models/soundconsole.rb
class Soundconsole < ActiveRecord::Base
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
validates :firstname, presence: true
validates :lastname, presence: true
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

end

app/models/used_sale.rb
class UsedSale < ActiveRecord::Base
end

app/models/wiredmic.rb
class Wiredmic < ActiveRecord::Base
end

app/models/wirelessmic.rb
class Wirelessmic < ActiveRecord::Base
end

app/controllers/lighting_products_controller.rb
class LightingProductsController < ApplicationController
  before_action :set_lighting_product, only: [:show, :edit, :update, :destroy]

  # GET /lighting_products
  # GET /lighting_products.json
  def index
    @lighting_products = LightingProduct.all
  end

  # GET /lighting_products/1
  # GET /lighting_products/1.json
  def show
  end

  # GET /lighting_products/new
  def new
    @lighting_product = LightingProduct.new
  end

  #GET /lighting_products/1/edit
  def 
  end

  # POST /lighting_products
  # POST /lighting_products.json
  def create
    @lighting_product = LightingProduct.new(lighting_product_params)

    respond_to do |format|
      if @lighting_product.save
        format.html { redirect_to @lighting_product, notice: 'Lighting product was successfully created.' }
        format.json { render :show, status: :created, location: @lighting_product }
      else
        format.html { render :new }
        format.json { render json: @lighting_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lighting_products/1
  # PATCH/PUT /lighting_products/1.json
  def update
    respond_to do |format|
      if @lighting_product.update(lighting_product_params)
        format.html { redirect_to @lighting_product, notice: 'Lighting product was successfully updated.' }
        format.json { render :show, status: :ok, location: @lighting_product }
      else
        format.html { render :edit }
        format.json { render json: @lighting_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lighting_products/1
  # DELETE /lighting_products/1.json
  def destroy
    @lighting_product.destroy
    respond_to do |format|
      format.html { redirect_to lighting_products_url, notice: 'Lighting product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lighting_product
      @lighting_product = LightingProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lighting_product_params
      params.require(:lighting_product).permit(:maker, :name, :quantity, :price, :type)
    end
end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lighting_products_helper.rb
module LightingProductsHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/lighting_products/_form.html.erb
<%= form_for(@lighting_product) do |f| %>
  <% if @lighting_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lighting_product.errors.count, "error") %> prohibited this lighting_product from being saved:</h2>

      <ul>
      <% @lighting_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :maker %><br>
    <%= f.text_field :maker %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lighting_products/edit.html.erb
<h1>Editing lighting_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @lighting_product %> |
<%= link_to 'Back', lighting_products_path %>

app/views/lighting_products/index.html.erb
<h1>Listing lighting_products</h1>

<table>
  <thead>
    <tr>
      <th>Maker</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lighting_products.each do |lighting_product| %>
      <tr>
        <td><%= lighting_product.maker %></td>
        <td><%= lighting_product.name %></td>
        <td><%= lighting_product.quantity %></td>
        <td><%= lighting_product.price %></td>
        <td><%= lighting_product.type %></td>
        <td> <%= link_to "Buy", new_newsale_path(:LightingProduct_id => LightingProduct) %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lighting product', new_lighting_product_path %>

app/views/lighting_products/new.html.erb
<h1>New lighting_product</h1>

<%= render 'form' %>

<%= link_to 'Back', lighting_products_path %>

app/views/lighting_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Maker:</strong>
  <%= @lighting_product.maker %>
</p>

<p>
  <strong>Name:</strong>
  <%= @lighting_product.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @lighting_product.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @lighting_product.price %>
</p>

<p>
  <strong>Type:</strong>
  <%= @lighting_product.type %>
</p>

<%= link_to 'Edit', edit_lighting_product_path(@lighting_product) %> |
<%= link_to 'Back', lighting_products_path %>