config/routes.rb
Rails.application.routes.draw do
  resources :sound_products

  resources :lighting_products

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :promotions

  get 'community/index'

  get 'productinfo/sound'

  get 'productinfo/light'

    get 'home/search'
    post 'home/search'

resources :lightingconsoles

  resources :lightingaccessories

  resources :lightingcables

  resources :movingfixtures

  resources :ledfixtures

  resources :conventionalfixtures

  resources :amplifers

  resources :speakers

  resources :soundcables

  resources :soundconsoles

  resources :wiredmics

  resources :wirelessmics

  resources :employees

  resources :rentals

  resources :newsales

  resources :suppliers

  resources :used_sales

  resources :customers

    get 'home/sales'

    get 'home/rentals'

    get 'home/index'

    get 'home/about'

    get 'home/contact'
    
    get 'home/help'

    get 'home/privacy'
    
    get 'home/info'
    
    get 'home/weekend'
    
    get 'home/announcements'
    get 'home/conditions'
    get 'home/sitemap'

    get "login" => "sessions#new", :as => "login"
delete 'logout' => "sessions#destroy", :as => "logout"
resources :sessions

  root 'home#index'

end

app/models/amplifer.rb
class Amplifer < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :firstname, presence: true
validates :lastname, presence: true

  class EmailValidator < ActiveModel::EachValidator
        def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end
      validates :username, :presence => true, :uniqueness => true
	has_secure_password

end

app/models/employee.rb
class Employee < ActiveRecord::Base
validates :firstname, presence: true
validates :lastname, presence: true

   class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

end

app/models/ledfixture.rb
class Ledfixture < ActiveRecord::Base
end

app/models/lightingcable.rb
class Lightingcable < ActiveRecord::Base
end

app/models/lightingconsole.rb
class Lightingconsole < ActiveRecord::Base
end

app/models/movingfixture.rb
class Movingfixture < ActiveRecord::Base
end

app/models/newsale.rb
class Newsale < ActiveRecord::Base
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
end

app/models/rental.rb
class Rental < ActiveRecord::Base
end

app/models/sound_product.rb
class SoundProduct < ActiveRecord::Base
end

app/models/soundcable.rb
class Soundcable < ActiveRecord::Base
end

app/models/soundconsole.rb
class Soundconsole < ActiveRecord::Base
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
validates :firstname, presence: true
validates :lastname, presence: true
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

end

app/models/used_sale.rb
class UsedSale < ActiveRecord::Base
end

app/models/wiredmic.rb
class Wiredmic < ActiveRecord::Base
end

app/models/wirelessmic.rb
class Wirelessmic < ActiveRecord::Base
end

app/controllers/lightingconsoles_controller.rb
class LightingconsolesController < ApplicationController
  before_action :set_lightingconsole, only: [:show, :edit, :update, :destroy]

  # GET /lightingconsoles
  # GET /lightingconsoles.json
  def index
    @lightingconsoles = Lightingconsole.all
  end

  # GET /lightingconsoles/1
  # GET /lightingconsoles/1.json
  def show
  end

  # GET /lightingconsoles/new
  def new
    @lightingconsole = Lightingconsole.new
  end

  # GET /lightingconsoles/1/edit
  def edit
  end

  # POST /lightingconsoles
  # POST /lightingconsoles.json
  def create
    @lightingconsole = Lightingconsole.new(lightingconsole_params)

    respond_to do |format|
      if @lightingconsole.save
        format.html { redirect_to @lightingconsole, notice: 'Lightingconsole was successfully created.' }
        format.json { render :show, status: :created, location: @lightingconsole }
      else
        format.html { render :new }
        format.json { render json: @lightingconsole.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lightingconsoles/1
  # PATCH/PUT /lightingconsoles/1.json
  def update
    respond_to do |format|
      if @lightingconsole.update(lightingconsole_params)
        format.html { redirect_to @lightingconsole, notice: 'Lightingconsole was successfully updated.' }
        format.json { render :show, status: :ok, location: @lightingconsole }
      else
        format.html { render :edit }
        format.json { render json: @lightingconsole.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lightingconsoles/1
  # DELETE /lightingconsoles/1.json
  def destroy
    @lightingconsole.destroy
    respond_to do |format|
      format.html { redirect_to lightingconsoles_url, notice: 'Lightingconsole was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lightingconsole
      @lightingconsole = Lightingconsole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lightingconsole_params
      params.require(:lightingconsole).permit(:consolemaker, :consolemodel, :universe, :externalscreens, :consolequantity, :productimage)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lightingconsoles_helper.rb
module LightingconsolesHelper
end

app/helpers/newsales_helper.rb
module NewsalesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/lightingconsoles/_form.html.erb
<%= form_for(@lightingconsole) do |f| %>
  <% if @lightingconsole.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lightingconsole.errors.count, "error") %> prohibited this lightingconsole from being saved:</h2>

      <ul>
      <% @lightingconsole.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :consolemaker %><br>
    <%= f.text_field :consolemaker %>
  </div>
  <div class="field">
    <%= f.label :consolemodel %><br>
    <%= f.text_field :consolemodel %>
  </div>
  <div class="field">
    <%= f.label :universe %><br>
    <%= f.number_field :universe %>
  </div>
  <div class="field">
    <%= f.label :externalscreens %><br>
    <%= f.check_box :externalscreens %>
  </div>
  <div class="field">
    <%= f.label :consolequantity %><br>
    <%= f.number_field :consolequantity %>
  </div>
  <div class="field">
    <%= f.label :productimage %><br>
    <%= f.text_field :productimage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lightingconsoles/edit.html.erb
<h1>Editing lightingconsole</h1>

<%= render 'form' %>

<%= link_to 'Show', @lightingconsole %> |
<%= link_to 'Back', lightingconsoles_path %>

app/views/lightingconsoles/index.html.erb
<h1>Listing lightingconsoles</h1>

<table>
  <thead>
    <tr>
      <th>Consolemaker</th>
      <th>Consolemodel</th>
      <th>Universe</th>
      <th>Externalscreens</th>
      <th>Consolequantity</th>
      <th>Productimage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lightingconsoles.each do |lightingconsole| %>
      <tr>
        <td><%= lightingconsole.consolemaker %></td>
        <td><%= lightingconsole.consolemodel %></td>
        <td><%= lightingconsole.universe %></td>
        <td><%= lightingconsole.externalscreens %></td>
        <td><%= lightingconsole.consolequantity %></td>
        <td><%= lightingconsole.productimage %></td>
        <td><%= link_to 'Show', lightingconsole %></td>
        <td><%= link_to 'Edit', edit_lightingconsole_path(lightingconsole) %></td>
        <td><%= link_to 'Destroy', lightingconsole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lightingconsole', new_lightingconsole_path %>

app/views/lightingconsoles/new.html.erb
<h1>New lightingconsole</h1>

<%= render 'form' %>

<%= link_to 'Back', lightingconsoles_path %>

app/views/lightingconsoles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Consolemaker:</strong>
  <%= @lightingconsole.consolemaker %>
</p>

<p>
  <strong>Consolemodel:</strong>
  <%= @lightingconsole.consolemodel %>
</p>

<p>
  <strong>Universe:</strong>
  <%= @lightingconsole.universe %>
</p>

<p>
  <strong>Externalscreens:</strong>
  <%= @lightingconsole.externalscreens %>
</p>

<p>
  <strong>Consolequantity:</strong>
  <%= @lightingconsole.consolequantity %>
</p>

<p>
  <strong>Productimage:</strong>
  <%= @lightingconsole.productimage %>
</p>

<%= link_to 'Edit', edit_lightingconsole_path(@lightingconsole) %> |
<%= link_to 'Back', lightingconsoles_path %>